package com.apartment.exception;

public enum ErrorCode {
    // Auth
    AUTH_CODE_FORMAT_INVALID("auth.CODE_FORMAT_INVALID"),
    AUTH_PHONE_NOT_REGISTERED("auth.PHONE_NOT_REGISTERED"),
    AUTH_PHONE_IN_USE("auth.PHONE_IN_USE"),
    AUTH_USER_NOT_FOUND("auth.USER_NOT_FOUND"),
    USER_EMAIL_REQUIRED("user.EMAIL_REQUIRED"),

    // Order
    ORDER_ROOM_EMPTY("order.ROOM_EMPTY"),
    ORDER_DATES_EMPTY("order.DATES_EMPTY"),
    ORDER_END_BEFORE_START("order.END_BEFORE_START"),
    ORDER_ROOM_NO_EMPTY("order.ROOM_NO_EMPTY"),
    ORDER_ROOM_TIME_CONFLICT("order.ROOM_TIME_CONFLICT"),
    ORDER_ROOM_MAINTENANCE("order.ROOM_MAINTENANCE"),
    ORDER_OCCUPANT_CONFLICT("order.OCCUPANT_CONFLICT"),
    ORDER_INDIVIDUAL_ONE_CURRENT("order.INDIVIDUAL_ONE_CURRENT"),
    ORDER_NOT_FOUND("order.NOT_FOUND"),
    ORDER_NO_ROOM_RECORDS("order.NO_ROOM_RECORDS"),
    ORDER_ROOM_CARD_EMPTY("order.ROOM_CARD_EMPTY"),
    ORDER_DOOR_CODE_EMPTY("order.DOOR_CODE_EMPTY"),
    ORDER_CANCEL_DEADLINE_PASSED("order.CANCEL_DEADLINE_PASSED"),
    ORDER_ALREADY_EXISTS("order.ALREADY_EXISTS"),
    ORDER_OCCUPY_NOT_FOUND("order.OCCUPY_NOT_FOUND"),
    ORDER_TIME_CONFLICT("order.TIME_CONFLICT"),
    ORDER_MAINTENANCE_CONFLICT("order.MAINTENANCE_CONFLICT"),
    ORDER_OCCUPANT_TIME_CONFLICT("order.OCCUPANT_TIME_CONFLICT"),
    ORDER_KEY_BOX_NO_EMPTY("order.KEY_BOX_NO_EMPTY"),
    ORDER_BOX_PASSWORD_EMPTY("order.BOX_PASSWORD_EMPTY"),
    ORDER_ROOM_DIRTY("order.ROOM_DIRTY"),
    ORDER_GROUP_NAME_EMPTY("order.GROUP_NAME_EMPTY"),
    ORDER_CONTACT_NAME_EMPTY("order.CONTACT_NAME_EMPTY"),
    ORDER_CONTACT_PHONE_EMPTY("order.CONTACT_PHONE_EMPTY"),
    ORDER_COMPANY_EMPTY("order.COMPANY_EMPTY"),
    ORDER_COST_CENTER_EMPTY("order.COST_CENTER_EMPTY"),
    ORDER_ACTIVITY_CODE_EMPTY("order.ACTIVITY_CODE_EMPTY"),

    // Maintenance
    MAINT_START_AFTER_END("maint.START_AFTER_END"),
    MAINT_ORDER_CONFLICT("maint.ORDER_CONFLICT"),
    MAINT_OTHER_CONFLICT("maint.OTHER_CONFLICT"),
    MAINT_COMPLETED_NO_REVERT("maint.COMPLETED_NO_REVERT"),
    MAINT_COMPLETED_NO_DELETE("maint.COMPLETED_NO_DELETE"),
    MAINT_ACTIVE_NO_DELETE("maint.ACTIVE_NO_DELETE"),

    // Notification
    NOTIF_RECIPIENT_MISSING("notif.RECIPIENT_MISSING"),
    NOTIF_UNKNOWN_CHANNEL("notif.UNKNOWN_CHANNEL"),

    // General
    PARAM_ERROR("general.PARAM_ERROR"),
    GENERAL_EXCEL_FAILED("general.EXCEL_FAILED"),
    GENERAL_ORDER_NOT_FOUND("general.ORDER_NOT_FOUND"),
    GENERAL_ROOM_NOT_FOUND("general.ROOM_NOT_FOUND"),
    GENERAL_OCCUPY_NOT_FOUND("general.OCCUPY_NOT_FOUND");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
