spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:postgresql://192.168.1.6:15432/apartment-mng2
    username: hxl
    password: asd12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 10080

wecom:
  corpid: ${WECOM_CORPID:ww250a982fbe9d08da}
  secret: ${WECOM_SECRET:hdTto-F2mSMpMbDuHURzQaUTHEBurCyVeHeubHxWAI0}
  agentid: ${WECOM_AGENTID:1000003}
  token: ${WECOM_TOKEN:s689tN6pZSAvDJm88VM6QVA3}
  encoding-aes-key: ${WECOM_ENCODING_AES_KEY:7CiOlMDrLPYNIm5xzaDtk1YopqOp6yIBOSSNPJyDJfs}
  callback:
    base-url: ${WECOM_CALLBACK_BASE_URL:http://ghome.genesismedtech.com}

file:
  upload-path: ${FILE_UPLOAD_PATH:./uploads}
